---
baseURL: https://volley-club-nogent.fr/
title: Volley Club Nogentais
author: Henri Buyse

timeZone: Europe/Paris
locale: fr-fr

# Multilingual
defaultContentLanguage: fr
defaultContentLanguageInSubdir: false
disableHugoGeneratorInject: true

enableRobotsTXT: true
enableGitInfo: false
enableEmoji: true
# sectionPagesMenu: main
# googleAnalytics: UA-1511XXXX-X

module:
  hugoVersion:
    extended: true
    min: 0.99.1
    max: ""
  mounts:
    - source: assets
      target: static
    - source: static
      target: static
    - source: assets
      target: assets
    - source: hugo_stats.json
      target: assets/notwatching/hugo_stats.json
      disableWatch: true

build:
  buildStats:
    enable: true
  cachebusters:
    - source: assets/notwatching/hugo_stats\.json
      target: css
    - source: tailwind\.config\.js
      target: css

security:
  exec:
    allow:
      - ^(dart-)?sass(-embedded)?$
      - ^go$
      - ^git$
      - ^node$
      - ^npx$
      - ^postcss$
      - ^tailwindcss$

taxonomies:
  category: categories
  tag: tags
