---
fr:
  languageName: French
  languageCode: fr-FR
  weight: 10
  params:
    languageISO: FR
  pagination:
    disableAliases: false
    pagerSize: 10
    path: page

en:
  languageName: English
  languageCode: en-US
  weight: 20
  params:
    languageISO: EN
  pagination:
    disableAliases: false
    pagerSize: 10
    path: page
