---
main:
  - name: Accueil
    url: /
    weight: 10
  - name: Équipes
    url: /equipes/
    weight: 20
  - name: Beach
    url: /beach/
    weight: 25
  - name: Histoire
    url: /histoire/
    weight: 30
  - name: Actualites
    url: /actualites/
    weight: 40
  - name: Contact
    url: /contact/
    weight: 50
  - name: Inscriptions
    url: /inscriptions/
    weight: 60
