---
main:
  - name: Home
    url: /
    weight: 10
  - name: Teams
    url: /equipes/
    weight: 20
  - name: Beach
    url: /beach/
    weight: 25
  - name: History
    url: /histoire/
    weight: 30
  - name: Posts
    url: /actualites/
    weight: 40
  - name: Contact
    url: /contact/
    weight: 50
  - name: Registration
    url: /inscriptions/
    weight: 60
