[[main]]
name = "Accueil"
url = "/"
weight = 10

[[main]]
name = "Équipes"
url = "/equipes/"
weight = 20

[[main]]
name = "Projets"
url = "/projets/"
weight = 30

[[main]]
name = "Histoire"
url = "/histoire/"
weight = 40

[[main]]
name = "Actualites"
url = "/actualites/"
weight = 50

[[main]]
name = "Contact"
url = "/contact/"
weight = 60
