---
description: Site officiel du Volley Club Nogentais
adhesionLink: "https://www.helloasso.com/associations/volley-club-nogentais/adhesions/fsgt2526/"
hasBreadcrumb: false
banner:
  enable: false

socials:
  facebook:
    icon: "facebook-f"
    url: "https://www.facebook.com/VolleyClubNogent/"
  instagram:
    icon: "instagram"
    url: "https://www.instagram.com/volleyclubnogent/"
  youtube:
    icon: "youtube"
    url: "https://www.youtube.com/@volleyclubnogent"

logo:
  # January to May
  - logo_couleur.svg
  - logo_couleur.svg
  - logo_couleur.svg
  - logo_couleur.svg
  - logo_couleur.svg
  # June to August
  - beach_logo_color.svg
  - beach_logo_color.svg
  - beach_logo_color.svg
  # September
  - logo_couleur.svg
  # October
  - logo_rose.svg
  # November
  - logo_couleur.svg
  # December
  - logo_couleur.svg
