---
printWidth: 120
tabWidth: 2
useTabs: false
semi: false
singleQuote: true
trailingComma: 'es5'
bracketSpacing: true
arrowParens: avoid
proseWrap: always
plugins:
  - prettier-plugin-go-template
overrides:
  - files: '*.html'
    options:
      parser: go-template
