---
services:
  hugo:
    image: hugomods/hugo:exts-non-root
    container_name: volley-hugo
    ports:
      - '1313:1313'
    volumes:
      - ./:/src
    command: server --bind 0.0.0.0 --baseURL=http://localhost/ --buildDrafts --buildFuture --enableGitInfo=true --disableFastRender
    depends_on:
      merge:
        condition: service_completed_successfully

  fsgt_download:
    image: python:alpine
    volumes:
      - ./scripts/:/app
      - ./data/:/data
    command: python /app/fsgt-get-calendars.py

  ffvb_download:
    image: python:alpine
    volumes:
      - ./scripts/:/app
      - ./data/:/data
    command: python /app/ffvb-get-calendars.py

  merge:
    image: python:alpine
    volumes:
      - ./scripts/:/app
      - ./data/:/data
    command: python /app/merge-next-games.py
    depends_on:
      fsgt_download:
        condition: service_completed_successfully
      ffvb_download:
        condition: service_completed_successfully
