---
name: "Pre-Commit"

on:
  pull_request:
  push:
    branches:
      - main
      - feat/**
      - fix/**

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Do a git checkout including submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install Node.js dependencies
        run: "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"

      - name: Cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
