---
name: "Pre-Commit"

on:
  pull_request:
  push:
    branches:
      - main
      - feat/**
      - fix/**

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install Prettier
        run: npm install prettier prettier-plugin-go-template

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

      - name: Run pre-commit.ci
        uses: pre-commit-ci/lite-action@v1.1.0
        if: always()
